name: Check PyPI Secret Availability

on:
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check PYPI_TOKEN Secret
        run: |
          if [ -z "${{ secrets.PYPI_TOKEN }}" ]; then
            echo "PYPI_TOKEN secret is not available."
            exit 1
          else
            echo "PYPI_TOKEN secret is available."
          fi
