name: Check PyPI Secret Availability

on:
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check PYPI_PASIR_ALL Secret
        run: |
          if [ -z "${{ secrets.PYPI_PASIR_ALL }}" ]; then
            echo "PYPI_PASIR_ALL secret is not available."
            exit 1
          else
            echo "PYPI_PASIR_ALL secret is available."
          fi
