name: Check PyPI Secret

on:
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check PYPI_PASIR Secret
        run: |
          if [ -z "${{ secrets.PYPI_PASIR }}" ]; then
            echo "PYPI_PASIR secret is not available."
            exit 1
          else
            echo "PYPI_PASIR secret is available."
          fi
